### ISSUE TITLE
Grossansicht/neues Fenster

### ISSUE THREAD

**Issue by sfx12** [fritzmg/contao-facebook-gallery#2]
Hallo,

benutze conta 3.5.2 und Facebook Gallery 1.21.9006 mit grid_33.

Leider geht kein Grossansicht (nicht klickbar im FE.

LG sfx12

**Comment by fritzmg** [comment]
Hm, hast du einen Link zur Seite?

**Comment by sfx12** [comment]
web124.s0.udvp.de gleich erster content die 6 bilder

PS: habe Gallery grid_34 Template (bootstrap) aber mit anderen templates geht es auch nicht

**Comment by sfx12** [comment]
kann man vielleicht direkt im Template das rel"lightbox" einbauen bzw. nutze colorbox !

[grid_34.txt](https://github.com/fritzmg/contao-facebook-gallery/files/85720/grid_34.txt)

**Comment by fritzmg** [comment]
Kann das Problem leider nicht nachvollziehen. Wenn das dein Template ist, dann sollte rein theoretisch bei dir in `$col->href` nichts drinstehen, warum auch immer.

**Comment by sfx12** [comment]
wie nichts drinstehen ? im Template direkt ? oder bei der Ausgabe ?

**Comment by fritzmg** [comment]
In den Template Daten. In `$col->href` sollte eigentlich die URL zum "Originalbild" auf Facebook stehen (bzw. die URL zur größten bei Facebook abgespeicherten Version des Bildes).

Was für eine Album ID ist das?

**Comment by fritzmg** [comment]
Hab' das Problem gefunden, ist nun in Version `1.2.2` behoben.

**Comment by sfx12** [comment]
ahh, ok cool !! dürft ich erfahren woran das Problem lag ?

lg sfx

**Comment by fritzmg** [comment]
Den Bug habe ich mit Version `1.1.10` [eingebaut](https://github.com/fritzmg/contao-facebook-gallery/blob/1.1.10/system/modules/facebook_gallery/elements/ContentFacebookGallery.php#L196), womit ich die Extension mit Contao 3.4 und aufwärts kompatibel gemacht habe - aber gleichzeitig habe ich dadurch irrtümlich bestimmte Daten wie zB den `href` zum Original auch nicht mehr an das Template weitergegeben (unter Contao `>= 3.4`).
