### ISSUE TITLE
Gallery - "exactes format"

### ISSUE THREAD

**Issue by sfx12** [fritzmg/contao-facebook-gallery#3]
Leider noch ein Bug glaub ich, bei Bildgröße reagieren die Thumbs nicht wenn man z.b exactes Format 200 x 200 px wählt !!

LG sfx12

**Comment by fritzmg** [comment]
Doch, also theoretisch sollte es so sein:

> You can also define an image width and/or height (the image size mode will be ignored) - however, this will not be exact. Facebook (usually) provides differently sized images for each image of the album - the content element will try to find the smallest image that is at least as large as the given width and/or height. Thus you'll probably have to resize the images via CSS, to fit in your layout. Or change the `gallery_default` template and hardcode the given size as an inline style.

Siehe die [README](https://github.com/fritzmg/contao-facebook-gallery/blob/1.2.2/README.md).

Geplant ist jedoch, dass man [in einer zukünftigen Version](https://github.com/fritzmg/contao-facebook-gallery/issues/1) über eine System Einstellung auswählen kann, dass die Facebook Bilder generell auf die Contao Installation herunter geladen werden und somit dann die Thumbnail Bildgröße von Contao exakt prozessiert werden kann.

**Comment by fritzmg** [comment]
Closed in favor of #1
