### ISSUE TITLE
Facebook Funktionen zum Album hinzufügen

### ISSUE THREAD

**Issue by Stetto** [fritzmg/contao-facebook-gallery#4]
Es wäre für eine nächste Version total super, wenn man erweiterte Facebook-Funktionen zu eurem tollen Paket hinzufügen könnte.

Die Facebook-Galerie funktioniert unkompliziert und auf Anhieb. 

Insbesondere Priorisiert wäre toll
- Der Albumname
- Der Bildtext
- Like-Button

Alles andere wäre noch ein zusätzliches Leckerli.

![fbgalerie](https://cloud.githubusercontent.com/assets/24955181/23741357/623540ba-04a8-11e7-9072-bf94e3d505d2.png)

**Comment by Stetto** [comment]
Ein Tipp wäre allerdings ebenfalls cool. Ich beschäftige mich auch selbst damit, bin allerdings Laie :) so ein Wink mit dem Zaunpfahl, an welcher Stelle/Datei ich welche Infos ergänzen muss, wäre super.

**Comment by fritzmg** [comment]
Die ersten zwei Dinge sind wahrscheinlich möglich, der Like Button nicht, denn das hängt von Faktoren ab, die nicht von dieser Extension berücksichtigt werden können.

**Comment by fritzmg** [comment]
Aus deinem Mock-Up entnehme ich, dass du den Album Titel gerne in der Default Color Box als Titel haben möchtest. Das würde bedeuten, dass man den Album Title beim `title` Attribute des Links des Bildes ausgeben müsste (in der Default Konfiguration).

Das wiederum halte nich nicht für sinnvoll und werde es daher auch so nicht implementieren. Was ich jedoch schon implementiert habe:

* man kann nun den Bildtext als Caption ausgeben lassen
* man kann den Albumtitel automatisch als Überschrift der Galerie ausgeben lassen

Damit du das mit der Colorbox erreichen kannst werde ich aber einbauen, dass du pro Galerie Item auch den Album Titel bekommst und das daher in einem eigenen `gallery_default` Template umsetzen könntest.
